### ISSUE TITLE
Porting to Teensy 4.0

### ISSUE THREAD

**Issue by mjs513** [michaelerule/Uno9341TFT#2]
Hi Michael
With the release of the Teensy 4.0 (https://www.pjrc.com/store/teensy40.html) with 1MB memory and 600Mhz clock I finished porting over your code to that processor.  I didn't implement exactly the way you did because, frankly, you lost me of some stuff.  Specifically using frame ID.

The Teensy family of processors has its own display drivers that support frame buffering and dma.  I did manage to get some descent results with the code but not great - getting some tearing in the shaded models (think that right - the edge interfaces show black sometimes) but getting smooth rotations using the built in frame buffer. 

Anyway guess the question is how can I disentangle frameID from your code, I did read your blog but got a little lost.  Looking at your code the biggest place its used is in colorPixel and interpolateHLine.  

Any help or pointers will be appreciated.

**Comment by michaelerule** [comment]
Hi mjs,

Yes, my write-up was not as clear as it should be. 

### Using Teensy

If the Teensy has its own display buffers, you might be able to implement double buffering, or at least read back the previous frame color data from this internal buffer. 

If I recall correctly, the TFT displays come with a custom driver chip. The documentation for this chip is incompletely translated from Chinese, and its not clear to me that all TFT displays on the market are fully compliant with the documentation. 

That said, in theory I remember reading a section of the datasheet that appears to support double-buffering, or at least some sort of whole-screen update. I think it might not be true double-buffering, but more like "sync to vblank". If you're able to push color data fast enough to the screen, you might be able to avoid the appearance of any intermediate drawing commands that cause "flicker".

One may be able to adapt the drawing commands to render into the Teensy's internal graphics buffer, then rapidly dump that color data to the screen. Even without double buffering or synchronizing with the display updates, this approach should avoid flicker since the intermediate drawing commands are never shown on the screen. You may still have some vertical "tearing" which is visible, while the new pixels overwrite the old ones. 

### The frameID bit and erasing on the Arduino

If any of the above methods work to reduce flickering, then I think there is no need to use the approach that I took with the Arduino. 

However, if it is not possible to avoid intermediate drawing commands being visible on the display, then the draw-and-erase approach might be useful. The idea is general: draw the next frame without erasing anything, so that the background doesn't show through. Keep track (somewhere) of which pixels you updated on the frame (that's one bit per pixel). Then, once it is drawn, go back and set all pixels that were not updated to the background color. 

It sounds like the Teensy has more memory, and it might be possible to store this bit mask on the microontroller. This should be much faster than pulling data back from the display.

One way that I sped up the drawing to the screen was to use only those colors with the same high- and low-byte. This allows one to avoid changing the data port states while drawing a straight line of a single color, which on the Arduino was a big performance boost (along with loop unrolling). In theory, it would be better to get the display to operate in 256 color mode, so that color data could be sent in half the time. But I was not able to get the driver chip to enter 256 color mode in my experiments. 

One of the reasons it was tricky to manipulate the ports fast enough to send color data is that the i/o pins on the Arduino breakout for sending color data go to various pins on different Ardunio ports (A/B/C/D). This increased the amount of i/o read-write instructions needed to specify a color. Since you're wiring up the Teensy by hand, it would be much better to send all of the parallel i/o lines to a set of pins that map to a single port, to further reduce i/o overhead. 

(The more complex pin mappings, and the lack of sufficient code space to include loop unrolling, were one of the reasons that the performance on the Arduino Leonardo was so much worse than on the Duemilenova). 

It's been a while since I've looked at this code, but let's see. The frameID bit is either 1 or 0, so we can distinguish between the current and previous frames. I think I might have XOR-ed the frameID by the last bit of the line #, so that the resulting color changes of flipping this bit are less noticeable (DITHERED_MASK_FLAG). 

Drawing consists of two phases. First, we draw the new color data with the current frameID set. 
Then, we scan back over the image and look for any pixels that are not the background and have the old frameID bit. For mesh models, we actually re-draw the previous mesh model in masked mode, which erases any bits of lines from the previous frame that were not overwritten by new data. For the filled-triangle modes, we scan over the bounding box of the model.

## Overall

It sounds like you're getting very good performance using the internal framebuffer, and the frameID bit and the erasing phase are not necessary on this platform. In which case, you could use the existing code as-is and simply skip the erase step, instead opting to erase-and-redraw in the internal memory, and then copying that result to the display. 

With this setup, you should be able to get much better color resolution, especially if you hook up the TFT data lines to a single port on the Teensy that can be read/written with one instruction. In this case, the macros which manipulate the frameID bit, and which re-order color data for the Arduino ports, can be removed.

**Comment by mjs513** [comment]
Thanks for getting back to me so fast on this Michael - was pleasantly surprised :)

Have a better understanding now with whats going on in the code.  By the way - the write up was actually pretty good and found it very helpful.  With the Teensy the ILI9341 everything is done over SPI which I am running at 144Mhz so getting about 27 fps on shaded draw right now.

Haven't really played with 3d graphics since college days and that was a very very long time ago.

Gave me a bunch to think about on approaches so now guess back to work on this and a couple of other projects working in.
